// <auto-generated />
namespace OnlineMobileShop.Respository.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.4.0")]
    public sealed partial class mobilev3 : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(mobilev3));
        
        string IMigrationMetadata.Id
        {
            get { return "202003161138156_mobile-v3"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
